create table daruma_q (
    id int auto_increment primary key,
    createDate datetime,
    question1_1 varchar(5),
    question1_2 varchar(5),
    question1_3 varchar(5),
    question1_4 varchar(5),
    question1_5 varchar(5),
    question1_6 varchar(5),
    question2_1 varchar(5),
    question2_2 varchar(5),
    question3 varchar(5),
    question4 varchar(5),
    question5 varchar(5),
    question6_1 varchar(5),
    question6_2 varchar(5),
    question6_3 varchar(5),
    question6_4 varchar(5),
    question7 varchar(5),
    question8 varchar(5),
    email varchar(128),
    tel varchar(16) unique,
    message varchar(256)
);
